// <auto-generated />
using System;
using BusinessLogic.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessLogic.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20240109083907_AddMonsters")]
    partial class AddMonsters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AC")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4157234-1fc2-4710-8e76-d398cab9697d"),
                            AC = 23,
                            AttackModifier = 6,
                            AttackPerRound = 5,
                            Damage = 2,
                            DamageModifier = 2,
                            HitPoints = 22,
                            Name = "Monster1"
                        },
                        new
                        {
                            Id = new Guid("71c59502-89de-45c2-87cc-fdc83ce05898"),
                            AC = 16,
                            AttackModifier = 4,
                            AttackPerRound = 4,
                            Damage = 5,
                            DamageModifier = 2,
                            HitPoints = 15,
                            Name = "Monster2"
                        },
                        new
                        {
                            Id = new Guid("a08557ce-9156-4958-b78e-2ecc6cc13ede"),
                            AC = 21,
                            AttackModifier = 10,
                            AttackPerRound = 1,
                            Damage = 8,
                            DamageModifier = 5,
                            HitPoints = 46,
                            Name = "Monster3"
                        },
                        new
                        {
                            Id = new Guid("426f73d2-a8dc-4564-8dc0-c984219f1305"),
                            AC = 22,
                            AttackModifier = 3,
                            AttackPerRound = 5,
                            Damage = 6,
                            DamageModifier = 4,
                            HitPoints = 44,
                            Name = "Monster4"
                        },
                        new
                        {
                            Id = new Guid("dc1cbf3c-f4b1-4af8-a1e0-3b82cd94b49c"),
                            AC = 21,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = 4,
                            DamageModifier = 3,
                            HitPoints = 43,
                            Name = "Monster5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
