// <auto-generated />
using System;
using BusinessLogic.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusinessLogic.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AC")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("390d5ae7-7be4-4eae-bd64-748fafa0a049"),
                            AC = 3,
                            AttackModifier = 10,
                            AttackPerRound = 3,
                            Damage = "1d20",
                            DamageModifier = 1,
                            HitPoints = 26,
                            Name = "Monster1"
                        },
                        new
                        {
                            Id = new Guid("4dffb04a-44ec-4c32-bce3-2f5cac57a993"),
                            AC = 13,
                            AttackModifier = 1,
                            AttackPerRound = 1,
                            Damage = "1d8",
                            DamageModifier = 4,
                            HitPoints = 46,
                            Name = "Monster2"
                        },
                        new
                        {
                            Id = new Guid("ffaa3f1d-a1e6-4a38-8550-dde3922cee63"),
                            AC = 15,
                            AttackModifier = 2,
                            AttackPerRound = 4,
                            Damage = "2d4",
                            DamageModifier = 4,
                            HitPoints = 21,
                            Name = "Monster3"
                        },
                        new
                        {
                            Id = new Guid("07cc2e2f-e7e9-4602-a152-84443ce179d9"),
                            AC = 12,
                            AttackModifier = 8,
                            AttackPerRound = 4,
                            Damage = "1d10",
                            DamageModifier = 3,
                            HitPoints = 4,
                            Name = "Monster4"
                        },
                        new
                        {
                            Id = new Guid("38c7eda9-f9d2-4ae0-8bd6-3bdf5fa6c69a"),
                            AC = 13,
                            AttackModifier = 3,
                            AttackPerRound = 1,
                            Damage = "1d12",
                            DamageModifier = 3,
                            HitPoints = 24,
                            Name = "Monster5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
